#!/usr/bin/env python3
"""Matched boundary-mapping CLI pair using the existing isolated runner."""
from __future__ import annotations

import hashlib
import importlib.util
import json
import math
import re
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
SPEC = importlib.util.spec_from_file_location(
    "_boundary_pair_engine", ROOT / "scripts" / "pilot_test_order_pair.py")
engine = importlib.util.module_from_spec(SPEC)
assert SPEC and SPEC.loader
SPEC.loader.exec_module(engine)
FIXTURE = ROOT / "tests" / "fixtures" / "boundary_test_order"
engine.CHANGED_FILE = "parcelquote/__main__.py"
engine.BASE_PROMPT = (
    "Extend ParcelQuote's successful JSON with money containing exactly currency USD "
    "and integer minor_units equal to total_cents. Preserve existing fields, calculation "
    "and validation. Read CONTRACT.md, TESTING.md and test-options.json. Change only "
    "parcelquote/__main__.py. Do not modify tests or contracts. After editing run one "
    "focused check from test-options.json, then always run the complete required suite: "
    + engine.REQUIRED_COMMAND + ". Report no source text in the final response."
)


def frozen_files(root):
    """Hash immutable candidate files, excluding generated bytecode."""
    return {
        str(path.relative_to(root)): hashlib.sha256(path.read_bytes()).hexdigest()
        for path in root.rglob("*")
        if path.is_file() and not path.is_symlink()
        and "__pycache__" not in path.parts
        and str(path.relative_to(root)) != engine.CHANGED_FILE
    }


_original_events = engine._event_receipts


def _event_receipts(lines, event_times, started):
    lines = list(lines)
    result = _original_events(lines, event_times, started)
    result["first_useful_error_ms"] = None
    result["first_useful_error_status"] = "not_observed"
    result["first_successful_relevant_check_ms"] = None
    pending = set()
    completed = set()
    for index, line in enumerate(lines):
        try:
            event = json.loads(line)
        except (TypeError, ValueError):
            continue
        if not isinstance(event, dict):
            continue
        item = engine._item(event)
        if not isinstance(item, dict):
            continue
        identifier = item.get("id")
        if not isinstance(identifier, str) or not 0 < len(identifier) <= 128:
            continue
        kind = engine._test_kind(item)
        if event.get("type") == "item.started" and kind == "contract":
            pending.add(identifier)
            continue
        if (event.get("type") != "item.completed" or identifier not in pending
                or identifier in completed or kind not in {None, "contract"}):
            continue
        completed.add(identifier)
        if index >= len(event_times):
            continue
        observed = event_times[index]
        if (isinstance(observed, bool) or not isinstance(observed, (int, float))
                or not math.isfinite(observed) or observed < started):
            continue
        output = item.get("aggregated_output", item.get("output"))
        code = item.get("exit_code")
        if not isinstance(output, str) or isinstance(code, bool) or not isinstance(code, int):
            continue
        elapsed = round((observed - started) * 1000, 2)
        marker = "test_money_representation_json_contract"
        if code != 0 and re.search(r"(?:FAIL|ERROR):\s*" + marker + r"\b", output):
            if result["first_useful_error_ms"] is None:
                result["first_useful_error_ms"] = elapsed
                result["first_useful_error_status"] = "observed"
        elif code == 0 and marker in output and re.search(r"^OK\s*$", output, re.MULTILINE):
            if result["first_successful_relevant_check_ms"] is None:
                result["first_successful_relevant_check_ms"] = elapsed
    return result


engine._event_receipts = _event_receipts
_original_arm = engine._run_arm


def _run_arm(**kwargs):
    fixture = kwargs["fixture"]
    before = frozen_files(fixture)
    result = _original_arm(**kwargs)
    result.setdefault("first_useful_error_ms", None)
    result.setdefault("first_useful_error_status", "unscored")
    result.setdefault("first_successful_relevant_check_ms", None)
    result["immutable_files_preserved"] = before == frozen_files(fixture)
    independent = {}
    for kind, command in [("unit", engine.UNIT_COMMAND),
                          ("contract", engine.CONTRACT_COMMAND),
                          ("required", engine.REQUIRED_COMMAND)]:
        try:
            run = subprocess.run(engine.shlex.split(command), cwd=fixture,
                                 capture_output=True, timeout=10)
            independent[kind] = run.returncode
        except (OSError, subprocess.TimeoutExpired):
            independent[kind] = None
    result["independent_validation"] = independent
    if not result["immutable_files_preserved"] or any(
        code != 0 for code in independent.values()
    ):
        result["cli_status"] = "failed"
    return result


engine._run_arm = _run_arm
_original_pair = engine.run_pair


def run_pair(**kwargs):
    kwargs.setdefault("fixture_source", FIXTURE)
    return _original_pair(**kwargs)


engine.run_pair = run_pair


def main(argv=None):
    return engine.main(argv)


if __name__ == "__main__":
    raise SystemExit(main())
