#!/usr/bin/env python3
"""Matched boundary-mapping CLI pair using the existing isolated runner."""
from __future__ import annotations

import hashlib
import importlib.util
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
SPEC = importlib.util.spec_from_file_location(
    "_boundary_pair_engine", ROOT / "scripts" / "pilot_test_order_pair.py")
engine = importlib.util.module_from_spec(SPEC)
assert SPEC and SPEC.loader
SPEC.loader.exec_module(engine)
FIXTURE = ROOT / "tests" / "fixtures" / "boundary_test_order"
engine.CHANGED_FILE = "parcelquote/__main__.py"
engine.BASE_PROMPT = (
    "Extend ParcelQuote's successful JSON with money containing exactly currency USD "
    "and integer minor_units equal to total_cents. Preserve existing fields, calculation "
    "and validation. Read CONTRACT.md, TESTING.md and test-options.json. Change only "
    "parcelquote/__main__.py. Do not modify tests or contracts. After editing run one "
    "focused check from test-options.json, then always run the complete required suite: "
    + engine.REQUIRED_COMMAND + ". Report no source text in the final response."
)


def frozen_files(root):
    """Hash immutable candidate files, excluding generated bytecode."""
    return {
        str(path.relative_to(root)): hashlib.sha256(path.read_bytes()).hexdigest()
        for path in root.rglob("*")
        if path.is_file() and not path.is_symlink()
        and "__pycache__" not in path.parts
        and str(path.relative_to(root)) != engine.CHANGED_FILE
    }


_original_arm = engine._run_arm


def _run_arm(**kwargs):
    fixture = kwargs["fixture"]
    before = frozen_files(fixture)
    result = _original_arm(**kwargs)
    result["immutable_files_preserved"] = before == frozen_files(fixture)
    independent = {}
    for kind, command in [("unit", engine.UNIT_COMMAND),
                          ("contract", engine.CONTRACT_COMMAND),
                          ("required", engine.REQUIRED_COMMAND)]:
        try:
            run = subprocess.run(engine.shlex.split(command), cwd=fixture,
                                 capture_output=True, timeout=10)
            independent[kind] = run.returncode
        except (OSError, subprocess.TimeoutExpired):
            independent[kind] = None
    result["independent_validation"] = independent
    # The legacy fixture's error markers do not describe this task.
    result["first_useful_error_ms"] = None
    result["first_useful_error_status"] = "unscored_boundary_marker"
    result["first_successful_relevant_check_ms"] = None
    if not result["immutable_files_preserved"] or any(
        code != 0 for code in independent.values()
    ):
        result["cli_status"] = "failed"
    return result


engine._run_arm = _run_arm
_original_pair = engine.run_pair


def run_pair(**kwargs):
    kwargs.setdefault("fixture_source", FIXTURE)
    return _original_pair(**kwargs)


engine.run_pair = run_pair


def main(argv=None):
    return engine.main(argv)


if __name__ == "__main__":
    raise SystemExit(main())
